Changes robot maximum speed limit
robocup-ssl-br/rules-ssl-el pull request #19
Opened 2024-05-04 21:02 UTC by joaocarloscampi

Defined at the meeting on April 20th, robots will have maximum velocity limitation to 1.5m/s.

2024-05-04 21:29 UTC, GiovannaNascimento42 approved these changes

2024-05-04 21:34 UTC, GiovannaNascimento42 commented
Forgot to leave a comment on the approval, but the changes are OK.

2024-05-05 18:13 UTC, ersaraujo requested changes

2024-05-05 18:13 UTC, ersaraujo commented on chapters/offenses.adoc
> +The robot must not exceed a speed of 1.5 meters per second.
```suggestion
The ball must not be touched by a robot, while the robot is partially or fully inside the opponent <<Defense Area, defense area>>.

===== Robot Speed
The robot must not exceed a speed of 1.5 meters per second.
```

2024-05-05 18:13 UTC, ersaraujo commented on chapters/offenses.adoc
> +The robot must not exceed a speed of 1.5 meters per second.
Added a line between topics. Otherwise, the visualization will be broken.

2024-05-15 18:03 UTC, ersaraujo commented on chapters/offenses.adoc
> +The robot must not exceed a speed of 1.5 meters per second.
@joaocarloscampi can you check this?

2024-05-15 18:43 UTC, ersaraujo approved these changes

2024-05-15 18:43 UTC, merged