Feat/change timeout rules
robocup-ssl-br/rules-ssl-el pull request #2
Opened 2024-04-25 15:36 UTC by joaocarloscampi

Com referência a Ata do dia 20/04/2024, segue as alterações feitas para a regra de Timeout:

**- Tempo total de timeouts alterado de 300 para 420 segundos:** Como o EL é uma categoria de entrada e é o primeiro ano de execução, mais tempo de timeout se faz necessário para auxiliar as equipes com eventuais problemas que possam ocorrer
**- Quantidade de timeouts alterada de 4 para 3:** Isso foi discutido para fazer as equipes pensarem mais quando forem realizar um timeout (estrategicamente), para evitar que o jogo pare a todo momento
**- Tempo de timeout no overtime alterado para 240 segundos:** Mesma justificativa do correspondente no tempo normal
**- Quantidade de timeouts no overtime alterado para 1:** Mesma justificativa do correspondente no tempo normal, a partir da discussão em reunião e com os execs

2024-04-27 20:34 UTC, joaocarloscampi commented
Quantidade de timeouts corrigida conforme discussão em reunião do dia 27/04 e discussões no discord. Agora voltamos a ter 4 solicitações de timeout em tempo regulamentar e 2 solicitações em prorrogação.

2024-04-28 01:30 UTC, rafael-lang requested changes
Linhas 35 e 47 estão com modificações referentes à arbitragem e não ao timeout.
Favor retirar essas modificações da PR e criar uma branch para que elas possam ser avaliadas lá.

2024-04-28 23:10 UTC, joaocarloscampi commented
Linhas retiradas referentes a arbitragem

2024-04-28 23:31 UTC, rafael-lang approved these changes
Alterações OK

2024-04-29 11:18 UTC, PedroPizarro approved these changes
Alterações OK.

2024-04-29 11:18 UTC, merged