removes divA and divB mentioning
robocup-ssl-br/rules-ssl-el pull request #23
Opened 2024-05-16 01:32 UTC by PedroPizarro

Removes all diA/diB mentioning from the rules.

2024-05-16 04:29 UTC, ersaraujo approved these changes

2024-05-16 11:02 UTC, JoaoVictor0508 approved these changes
LGTM

2024-05-16 13:18 UTC, joaocarloscampi requested changes, later dismissed
In appendix file line 126 still have a mention about div A/B.

2024-05-18 13:41 UTC, ersaraujo approved these changes

2024-05-18 13:43 UTC, merged