updates rules README by removing some ssl-regular mentions
robocup-ssl-br/rules-ssl-el pull request #31
Opened 2024-06-30 19:20 UTC by PedroPizarro

2024-07-01 18:43 UTC, ersaraujo requested changes

2024-07-01 18:43 UTC, ersaraujo commented on README.md
Why don't we maintain the automatic generation of files? I can help with that.

2024-07-01 18:48 UTC, PedroPizarro commented on README.md
We can keep it, we only must update and maintain it.
If you say that you can help with that, given a clear working process of CI, we as TC can maintain it (if no additional cost is involved, IMO).

2024-07-01 20:20 UTC, JoaoVictor0508 commented on README.md
I agree that we can keep it. Maybe we could create a basic documentation for future TCs.

2024-07-02 13:05 UTC, PedroPizarro commented on README.md
Great,
@JoaoVictor0508  @ersaraujo do you prefer to close this PR and create another one with the updated CI files/scripts, or just commit directly into this PR?

2024-07-04 01:05 UTC, joaocarloscampi commented on README.md
I agree that we can keep it too. This will help teams access all of the rules faster and more easily.

2024-07-06 13:40 UTC, PedroPizarro commented on README.md
@ersaraujo  @JoaoVictor0508  Should we close this PR and create another one, or you are going to commit directly into this PR?

2024-07-06 15:47 UTC, JoaoVictor0508 commented on README.md
We can keep this PR, or can open another one to keep it organized and mention this PR. I prefer the second. What do you think?

2024-07-25 12:58 UTC, closed without merging