changes rule book title
robocup-ssl-br/rules-ssl-el pull request #36
Opened 2024-06-30 19:24 UTC by PedroPizarro

2024-07-01 18:53 UTC, ersaraujo requested changes

2024-07-01 18:53 UTC, ersaraujo commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
Where did this RoboCupSoccer come from? Shouldn't we keep the category name? I believe the division is different, but it is still the basis of a RoboCup category.

2024-07-01 18:59 UTC, PedroPizarro commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
![Screenshot_20240701_155800](https://github.com/robocup-ssl-br/rules-ssl-el/assets/39956729/23c07b1b-af6b-407e-ac8b-6d99b4c71507)

The main idea of this PR was to create this discussion. IMO we are part of the RoboCupSoccer, from being a category inside the Small Size League (a RoboCupSoccer league).

2024-07-01 19:00 UTC, PedroPizarro commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
@rafael-lang @adamhenriquemp are we (SSL-EL) formally part of the RoboCupSoccer?

2024-07-01 19:05 UTC, ersaraujo commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
But SSL itself is formally "RoboCup Small Size League", I don't know if there is such a nomenclature for the categories besides the "RoboCup" prefix.
![image](https://github.com/robocup-ssl-br/rules-ssl-el/assets/44985807/6803ab05-236b-4310-a4c8-77a19d4d1162)

2024-07-01 19:13 UTC, PedroPizarro commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
That is a fair point about the SSL, however, I think the SSL official site is also missing the mention of RoboCupSoccer as well.

2024-07-04 01:24 UTC, joaocarloscampi commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
I think it isn't necessary to change the rule book title, especially because all of the rules in RoboCup mention SSL as 'RoboCup Small Size League'

2024-07-06 13:36 UTC, PedroPizarro commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
Ok, however, we should add the entry-level title as the rule book is for this category.

So should we agree on RoboCup Small Size League Entry Leve?

2024-07-06 17:46 UTC, GabrielCFranco commented on sslrules.adoc
> += Rules of the RoboCupSoccer - Small Size League - Entry Level
I also agree, should we close this PR?

2024-07-25 12:56 UTC, ersaraujo approved these changes

2024-07-25 12:58 UTC, GiovannaNascimento42 reviewed
I believe that leaving the title as it is, just adding the EL, is sufficient. For me, we can close this PR.

2024-07-25 12:59 UTC, GiovannaNascimento42 approved these changes

2024-07-25 12:59 UTC, merged